- name: Add DNS record to idm
  hosts: ipaserver
  become: true
  tasks:
    - name: Add DNS record
      freeipa.ansible_freeipa.ipadnsrecord:
        ipaadmin_password: "{{ idm_password }}"
        name: "{{ record_hostname }}"
        zone_name: {{ record_zone }}
        ip_address: "{{ record_ip }}"
        create_reverse: yes
        state: present
