- name: Clean up terraform deployment
  hosts: kvm_host
  become: true
  tasks:
    - include_role:
        name: kvm_cleanup
      vars:
        vm_hostname: "{{ item }}"
      with_items: "{{ infra }}"
