- name : create a centos 8 vm on remote kvm host
  hosts: hypervisor
  become: true
  tasks:
    - include_role:
        name: hosninabil.kvm_terraform.extend_disk
      vars:
        vm_hostname: 'http-server'
        size: 2G
    - include_role:
        name: hosninabil.kvm_terraform.add_disk
      vars:
        vm_hostname: 'http-server'
        disk_name: centos8_2
        disk_size: 10
        pool_path: /var/lib/libvirt/images
        vm_disk_target: vdb
