---
# tasks file for vmware_cleanup
- name: cleanup terraform deployment
  terraform:
    project_path: "/root/vsphere/{{ vsphere_hostname }}"
    state: absent
    purge_workspace: True
- name: Delete workspace
  file:
    path: "/root/vsphere/{{ vsphere_hostname }}"
    state: absent
