---
# tasks file for post-install
#hostname
- hostname:
    name: "{{ vm_hostname }}"
#ssh
- name: copy ssh config file
  copy:
    src: sshd_conf
    dest: /etc/ssh/sshd_conf
    owner: root
    group: root
    mode: 0640
  notify: Restart sshd
- name: reset selinux context in selinux enabled systems
  file:
    path: /etc/ssh/sshd_conf
    seuser: system_u
    setype: etc_t
  when: ansible_os_family == "RedHat"
- name: update system
  package:
    name: '*'
    state: latest
  notify: rebooot host and wait to confirm
- name: Flush handlers
  meta: flush_handlers
- name: install vnc server needed packages
  package:
    name: tigervnc-server, python3 ,python3-firewall, firewalld
    state: present
- name: Create the remote .vnc directory
  file:
    path: "/home/{{ user }}/.vnc"
    mode: 0755
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Generate vnc password
  shell: |
      echo {{ password }} | vncpasswd -f > /home/{{ user }}/.vnc/passwd
  become: false
- name: Template vnc service file
  template:
    src: vncserver@.service.j2
    dest: /etc/systemd/system/vncserver@.service
    owner: root
    group: root
    mode: 0644
  notify: Start & enable the vncserver
- name : Ensure firewalld is started
  service:
    name: firewalld
    state: started
- name: Ensure vnc firewall port is open
  firewalld:
    port: 5901/tcp
    state: enabled
    permanent: true
    immediate: true
