---
# tasks file for kvm_machine
- name: Set variables for Centos 7
  set_fact:
    vm_image_url: "{{ centos_7_url }}"
  when: centos_version == '7'
- name: Set variables for Centos 8
  set_fact:
    vm_image_url: "{{ centos_8_url }}"
  when: centos_version == '8'
- name: Create terraform deployment directory
  file:
    path: "/root/{{ vm_hostname }}"
    state: directory
    mode: '0755'
  #notify: Init terraform directory
- name: Create terraform deployment config directory
  file:
    path: "/root/{{ vm_hostname }}/config"
    state: directory
    mode: '0755'
#download generic cloud image
- name: Download generic cloud image
  get_url:
    url: "{{ vm_image_url }}"
    dest: "/root/{{ vm_hostname }}/centos_{{ centos_version }}.qcow2"
# deployment configuration
#copy terraform provider file
- name: Copy tf files
  copy:
    src: "{{ item }}"
    dest: "/root/{{ vm_hostname }}/{{ item }}"
  with_items:
    - main.tf
    - providers.tf
- name: Flush handlers
  meta: flush_handlers
- name: Template variable and cloud-init files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: variables.tf.j2, dest: '/root/{{ vm_hostname }}/variables.tf' }
    - { src: cloud_init.yaml.j2, dest: '/root/{{ vm_hostname }}/config/cloud_init.yaml' }
    - { src: network_config_static.yaml.j2, dest: '{{ vm_hostname }}/config/network-config' }
- name: Deploy terraform workload
  terraform:
    project_path: "/root/{{ vm_hostname }}"
    state: present
