---
# tasks file for haproxy
- name: Install required packages
  package:
    name: haproxy, python3-firewall, firewalld
    state: present
  when: ansible_distribution_major_version is match('8')
- name: Install required packages
  package:
    name: haproxy, python-firewall, firewalld
    state: present
  when: ansible_distribution_major_version is match('7')
# Configure rsyslog
- name: Configure imudp module in rsyslog
  lineinfile:
    path: /etc/rsyslog.conf
    line: "{{ item }}"
  with_items:
    - module(load="imudp")
    - input(type="imudp" port="514")
  notify: Restart and enable rsyslog service
- name: Ensure HAproy log config file exist
  file:
    path: /etc/rsyslog.d/haproxy.conf
    state: touch
- name: Configure HAproxy logging
  lineinfile:
    path: /etc/rsyslog.d/haproxy.conf
    line: local2.*        /var/log/haproxy.log
  notify: Restart and enable rsyslog service
- name: Add HAproxy confguration
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      frontend {{ lb_name }}-frontend
        bind {{ lb_ip }}:{{ lb_port }}
        default_backend {{ lb_name }}-backend
      backend {{ lb_name }}-backend
        mode {{ lb_mode }}
        balance {{ lb_balance }}
        stats enable

- name: Add loadbalanced servers configuration
  lineinfile:
    path: /etc/haproxy/haproxy.cfg
    line: "  server {{ item.dn }} {{ item.ip }}:{{ item.port }} check"
  loop: "{{ lb_server_list }}"
  notify: Restart and enable HAproxy
- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
- name: Ensure haproxy firewalld port is enabled
  firewalld:
    port: "{{ lb_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
