---
# vars file for kvm_machine
vm_volume_name: terraform_vm_volume
centos_7_url: https://cloud.centos.org/centos/7/images/CentOS-7-aarch64-GenericCloud-2003.qcow2
centos_8_url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2
vm_root_password: "password"
vm_user: nabil
vm_ip: 10.112.42.57/24
vm_gw: 10.112.42.254
vm_dns: 8.8.8.8
vm_hostname: terraform-ansible
vm_memory: 2048
vm_cpu: 1
vm_network: vlan42
vm_authorized_ssh: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8IynYT1n2ZjMgDeuMczQJzbnZXAvoxmXbFXlVq/o89hmjVia7vIZq+szlh3SqFBvyxAx8ysoem2Kx9jfaaN//2LdO99Rs6ZLMXBjPn1+ehv1X+b0CJoxyOJ3eBcz2du2VdYDMkvilZfrlfLTcKsMa2W/8bbFslaXyQJ1S39e81nniEcbkpLFVmVsYn9qB5KL73M+KJasT/WG3dGJfazOMqHAyQJBflfU9N/zxNuljpS28/bGjT6Z+2X97ySiCfK/HSZAd9dSAIXMmFuZCPCc8Ft5JeU+URBpM7nHQkyjR3DLBYt/IxCj9zf/YVQkhp2Hz1sQt6+viL8qPyP0fkof4gddMuUBAhtZPdyNFgsCdSxf59Q6kHsZH1xE2TtVa8GBXhBLK0MbvvKCdIChGLc92m4pXi2f5YFs2J9WvQVuhRF6Pu3OMaC+NKXKY3IEDNtsM7PdcNdrnqVkQrIq5zH0jHiBV53HabCUkJ4E0CDqY5TXju9UsQOjtROQ1wMO/Scc= nabil@nabil-pc
