---
# tasks file for upload_image
- name: Set variables for Centos 7
  set_fact:
    image_path: "{{ centos_7_path }}"
  when: os_dist == "centos" and os_version == '7'
- name: Set variables for Centos 8
  set_fact:
    image_path: "{{ centos_8_path }}"
  when: os_dist == "centos" and os_version == '8'
- name: Set variables for RHEL 7
  set_fact:
    image_path: "{{ rhel_7_path }}"
  when: dist_version == "rhel" and os_version == '7'
- name: Set variables for RHEL 8
  set_fact:
    image_path: "{{ rhel_8_path }}"
  when: os_dist == "rhel" and os_version == '8'  
- name: Create terraform vpshere directory
  file:
    path: "/root/vsphere/images/{{ image_name }}"
    state: directory
    mode: '0755'
- name:
- name: Copy terraform main file
  copy:
    src: main.tf
    dest: "/root/vsphere/images/{{ image_name }}/main.tf"
- name: Template terraform files
  template:
    src: variables.tf.j2
    dest: "/root/vsphere/images/{{ image_name }}/variables.tf"
